import type {
  Game,
  Highlight,
  NewsArticle,
  StandingItem,
  StandingsByLeague,   // ★ 追加
  StatLeader,
  LeaderBoardCategory,
} from './types';

// lib/mockData.ts
import { Game, StandingItem, Article, StatLeader } from './types';

// チーム定義
export const TEAMS: Record<string, any> = {
  T: { id: 'T', name: '阪神', fullName: '阪神タイガース', color: '#FFE100' },
  G: { id: 'G', name: '巨人', fullName: '読売ジャイアンツ', color: '#F97600' },
  DB: { id: 'DB', name: 'DeNA', fullName: '横浜DeNAベイスターズ', color: '#0055A5' },
  C: { id: 'C', name: '広島', fullName: '広島東洋カープ', color: '#FF0000' },
  S: { id: 'S', name: 'ヤクルト', fullName: '東京ヤクルトスワローズ', color: '#96C800' },
  D: { id: 'D', name: '中日', fullName: '中日ドラゴンズ', color: '#002569' },
};

// 今日の試合（ダミー）
export const TODAYS_GAMES: Game[] = [
  {
    id: '1',
    date: '2025-06-15',
    status: 'final',
    homeTeam: TEAMS.T,
    visitorTeam: TEAMS.G,
    homeScore: 4,
    visitorScore: 2,
    startTime: '14:00',
    stadium: '甲子園',
  },
  {
    id: '2',
    date: '2025-06-15',
    status: 'live',
    homeTeam: TEAMS.DB,
    visitorTeam: TEAMS.C,
    homeScore: 1,
    visitorScore: 3,
    inning: '6回表',
    startTime: '14:00',
    stadium: '横浜',
  },
  {
    id: '3',
    date: '2025-06-15',
    status: 'scheduled',
    homeTeam: TEAMS.S,
    visitorTeam: TEAMS.D,
    homeScore: 0,
    visitorScore: 0,
    startTime: '18:00',
    stadium: '神宮',
  },
];

export const STANDINGS: StandingsByLeague = {
  // セ・リーグ（左）
  central: [
    {
      league: 'セ・リーグ',
      rank: 1,
      teamShort: 'T',
      teamName: '阪神',
      wins: 35,
      losses: 20,
      draws: 2,
      winPct: 0.636,
      gb: '-',
      recent: '○○○●○',
      streak: '3連勝',
      runDiff: +65,
      runsScored: 210,
      runsAllowed: 145,
    },
    {
      league: 'セ・リーグ',
      rank: 2,
      teamShort: 'G',
      teamName: '巨人',
      wins: 33,
      losses: 22,
      draws: 3,
      winPct: 0.600,
      gb: '2.0',
      recent: '●○○○●',
      streak: '1連敗',
      runDiff: +40,
      runsScored: 198,
      runsAllowed: 158,
    },
    {
      league: 'セ・リーグ',
      rank: 3,
      teamShort: 'DB',
      teamName: 'DeNA',
      wins: 30,
      losses: 25,
      draws: 1,
      winPct: 0.545,
      gb: '5.0',
      recent: '○●○○○',
      streak: '3連勝',
      runDiff: +25,
      runsScored: 185,
      runsAllowed: 160,
    },
    {
      league: 'セ・リーグ',
      rank: 4,
      teamShort: 'C',
      teamName: '広島',
      wins: 27,
      losses: 27,
      draws: 2,
      winPct: 0.500,
      gb: '7.5',
      recent: '●●○●○',
      streak: '1連勝',
      runDiff: +5,
      runsScored: 170,
      runsAllowed: 165,
    },
    {
      league: 'セ・リーグ',
      rank: 5,
      teamShort: 'S',
      teamName: 'ヤクルト',
      wins: 24,
      losses: 30,
      draws: 3,
      winPct: 0.444,
      gb: '10.5',
      recent: '○●●●○',
      streak: '1連勝',
      runDiff: -20,
      runsScored: 160,
      runsAllowed: 180,
    },
    {
      league: 'セ・リーグ',
      rank: 6,
      teamShort: 'D',
      teamName: '中日',
      wins: 20,
      losses: 35,
      draws: 1,
      winPct: 0.364,
      gb: '15.0',
      recent: '●●○●●',
      streak: '2連敗',
      runDiff: -45,
      runsScored: 140,
      runsAllowed: 185,
    },
  ],

  // パ・リーグ（右）
  pacific: [
    {
      league: 'パ・リーグ',
      rank: 1,
      teamShort: 'H',
      teamName: 'ソフトバンク',
      wins: 36,
      losses: 18,
      draws: 3,
      winPct: 0.667,
      gb: '-',
      recent: '○○●○○',
      streak: '2連勝',
      runDiff: +70,
      runsScored: 220,
      runsAllowed: 150,
    },
    {
      league: 'パ・リーグ',
      rank: 2,
      teamShort: 'L',
      teamName: '西武',
      wins: 31,
      losses: 23,
      draws: 1,
      winPct: 0.574,
      gb: '5.0',
      recent: '○●○○●',
      streak: '1連敗',
      runDiff: +30,
      runsScored: 190,
      runsAllowed: 160,
    },
    {
      league: 'パ・リーグ',
      rank: 3,
      teamShort: 'B',
      teamName: 'オリックス',
      wins: 29,
      losses: 24,
      draws: 2,
      winPct: 0.547,
      gb: '6.5',
      recent: '●○○●○',
      streak: '1連勝',
      runDiff: +18,
      runsScored: 175,
      runsAllowed: 157,
    },
    {
      league: 'パ・リーグ',
      rank: 4,
      teamShort: 'F',
      teamName: '日本ハム',
      wins: 26,
      losses: 28,
      draws: 1,
      winPct: 0.481,
      gb: '10.0',
      recent: '○●●○●',
      streak: '1連敗',
      runDiff: -5,
      runsScored: 165,
      runsAllowed: 170,
    },
    {
      league: 'パ・リーグ',
      rank: 5,
      teamShort: 'M',
      teamName: 'ロッテ',
      wins: 23,
      losses: 31,
      draws: 1,
      winPct: 0.426,
      gb: '13.0',
      recent: '●○●●●',
      streak: '3連敗',
      runDiff: -30,
      runsScored: 150,
      runsAllowed: 180,
    },
    {
      league: 'パ・リーグ',
      rank: 6,
      teamShort: 'E',
      teamName: '楽天',
      wins: 20,
      losses: 34,
      draws: 2,
      winPct: 0.370,
      gb: '16.0',
      recent: '○●●●○',
      streak: '1連勝',
      runDiff: -38,
      runsScored: 148,
      runsAllowed: 186,
    },
  ],
};



// 個人成績リーダーズ
export const LEADERS = {
  central: {
    batting: [
      { rank: 1, player: '近本 光司', team: 'T', value: '.315' },
      { rank: 2, player: '牧 秀悟', team: 'DB', value: '.308' },
      { rank: 3, player: '岡本 和真', team: 'G', value: '.301' },
    ],
    // 必要なら homerun もここに
    homerun: [
      { rank: 1, player: '村上 宗隆', team: 'S', value: '18' },
      { rank: 2, player: '佐藤 輝明', team: 'T', value: '16' },
      { rank: 3, player: '岡本 和真', team: 'G', value: '15' },
    ],
  },
  pacific: {
    batting: [
      // ダミーデータでOK
      // { rank: 1, player: '〜', team: 'H', value: '.320' },
    ],
    homerun: [
      // ここもあとで埋める
    ],
  },
};


// ニュース記事
export const ARTICLES: Article[] = [
  {
    id: '1',
    title: '【分析】佐藤輝明の打撃改造は成功したのか？ データで見る「打球角度」の変化',
    summary: 'フライボール革命への適応か、それとも原点回帰か。最新のトラッキングデータから、好調の要因をセイバーメトリクスで紐解く。',
    category: 'コラム',
    publishedAt: '2025/06/15 10:00',
  },
  {
    id: '2',
    title: 'セ・リーグ前半戦総括：投高打低トレンドに変化の兆し',
    summary: '防御率ランキングの上位を独占していた投手陣に対し、各球団のアプローチが変化しつつある。',
    category: '戦評',
    publishedAt: '2025/06/14 21:00',
  },
];
